### ISSUE TITLE
Please enable IGPU with NootedRed

### ISSUE THREAD

**Issue by JavadRabe** [kalkmann/Legion-5600H-Hackintosh#8]
I read this guide 
https://elitemacx86.com/threads/how-to-enable-amd-integrated-graphics-apu-on-macos-clover-opencore.1156/

But i can't do that because this my first trying to install macos on legion 5 that has rtx! 
Can you make EFI for using only IGPU?

**Comment by kalkmann** [comment]
The mentioned site is not recommended. Use as a reference:
- https://forum.amd-osx.com/
- https://nootinc.github.io/guide
- https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html

My EFI was made available because I use the machine, but I don't provide production services for other EFIs.

If you search, you will find reference EFIs (with dgpu disabled) here on github.

Good luck!
